name: Run python-only unit tests

on:
  push:
  workflow_dispatch:

env:
  LANG: "en_US.UTF-8"

jobs:
  test-altoolbox:
    runs-on: ubuntu-latest
    name: Run python only unit tests
    steps:
      - name: locales
        run: |
            sudo locale-gen en_US.UTF-8
            # TODO(#104): run the tests while set to a different locale
            sudo update-locale LANG=en_US.UTF-8
      - uses: SuffolkLITLab/ALActions/pythontests@main
